/* 
 * Bundledocs.Web.Api
 *
 * Bundledocs Web Api (v1)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Bundledocs.Model
{
    /// <summary>
    /// SendBriefReceiptDownloadInvitationBean
    /// </summary>
    [DataContract]
    public partial class SendBriefReceiptDownloadInvitationBean :  IEquatable<SendBriefReceiptDownloadInvitationBean>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendBriefReceiptDownloadInvitationBean" /> class.
        /// </summary>
        /// <param name="BriefRowKey">BriefRowKey.</param>
        /// <param name="BriefReceiptRowKey">BriefReceiptRowKey.</param>
        /// <param name="EmailAddress">EmailAddress.</param>
        /// <param name="Password">Password.</param>
        /// <param name="Message">Message.</param>
        public SendBriefReceiptDownloadInvitationBean(string BriefRowKey = null, string BriefReceiptRowKey = null, string EmailAddress = null, string Password = null, string Message = null)
        {
            this.BriefRowKey = BriefRowKey;
            this.BriefReceiptRowKey = BriefReceiptRowKey;
            this.EmailAddress = EmailAddress;
            this.Password = Password;
            this.Message = Message;
        }
        
        /// <summary>
        /// Gets or Sets BriefRowKey
        /// </summary>
        [DataMember(Name="BriefRowKey", EmitDefaultValue=false)]
        public string BriefRowKey { get; set; }
        /// <summary>
        /// Gets or Sets BriefReceiptRowKey
        /// </summary>
        [DataMember(Name="BriefReceiptRowKey", EmitDefaultValue=false)]
        public string BriefReceiptRowKey { get; set; }
        /// <summary>
        /// Gets or Sets EmailAddress
        /// </summary>
        [DataMember(Name="EmailAddress", EmitDefaultValue=false)]
        public string EmailAddress { get; set; }
        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [DataMember(Name="Password", EmitDefaultValue=false)]
        public string Password { get; set; }
        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name="Message", EmitDefaultValue=false)]
        public string Message { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SendBriefReceiptDownloadInvitationBean {\n");
            sb.Append("  BriefRowKey: ").Append(BriefRowKey).Append("\n");
            sb.Append("  BriefReceiptRowKey: ").Append(BriefReceiptRowKey).Append("\n");
            sb.Append("  EmailAddress: ").Append(EmailAddress).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as SendBriefReceiptDownloadInvitationBean);
        }

        /// <summary>
        /// Returns true if SendBriefReceiptDownloadInvitationBean instances are equal
        /// </summary>
        /// <param name="other">Instance of SendBriefReceiptDownloadInvitationBean to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SendBriefReceiptDownloadInvitationBean other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.BriefRowKey == other.BriefRowKey ||
                    this.BriefRowKey != null &&
                    this.BriefRowKey.Equals(other.BriefRowKey)
                ) && 
                (
                    this.BriefReceiptRowKey == other.BriefReceiptRowKey ||
                    this.BriefReceiptRowKey != null &&
                    this.BriefReceiptRowKey.Equals(other.BriefReceiptRowKey)
                ) && 
                (
                    this.EmailAddress == other.EmailAddress ||
                    this.EmailAddress != null &&
                    this.EmailAddress.Equals(other.EmailAddress)
                ) && 
                (
                    this.Password == other.Password ||
                    this.Password != null &&
                    this.Password.Equals(other.Password)
                ) && 
                (
                    this.Message == other.Message ||
                    this.Message != null &&
                    this.Message.Equals(other.Message)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.BriefRowKey != null)
                    hash = hash * 59 + this.BriefRowKey.GetHashCode();
                if (this.BriefReceiptRowKey != null)
                    hash = hash * 59 + this.BriefReceiptRowKey.GetHashCode();
                if (this.EmailAddress != null)
                    hash = hash * 59 + this.EmailAddress.GetHashCode();
                if (this.Password != null)
                    hash = hash * 59 + this.Password.GetHashCode();
                if (this.Message != null)
                    hash = hash * 59 + this.Message.GetHashCode();
                return hash;
            }
        }
    }

}
