/* 
 * Bundledocs.Web.Api
 *
 * Bundledocs Web Api (v1)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Bundledocs.Model;
using Bundledocs.Client;

namespace Bundledocs.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGroupsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="activateGroupMembershipBean"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        OAuth2ApiResponseStrongUserGroupBean GroupsActivateGroupMembership (string authorization, ActivateGroupMembershipBean activateGroupMembershipBean);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="activateGroupMembershipBean"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        ApiResponse<OAuth2ApiResponseStrongUserGroupBean> GroupsActivateGroupMembershipWithHttpInfo (string authorization, ActivateGroupMembershipBean activateGroupMembershipBean);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="addGroupMemberBean"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        OAuth2ApiResponseStrongUserGroupBean GroupsAddGroupMember (string authorization, string partitionKey, string rowKey, EmailAddressBean addGroupMemberBean);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="addGroupMemberBean"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        ApiResponse<OAuth2ApiResponseStrongUserGroupBean> GroupsAddGroupMemberWithHttpInfo (string authorization, string partitionKey, string rowKey, EmailAddressBean addGroupMemberBean);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="userGroupBean"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        OAuth2ApiResponseStrongUserGroupBean GroupsCreateGroup (string authorization, UserGroupBean userGroupBean);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="userGroupBean"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        ApiResponse<OAuth2ApiResponseStrongUserGroupBean> GroupsCreateGroupWithHttpInfo (string authorization, UserGroupBean userGroupBean);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        OAuth2ApiResponseStrongUserGroupBean GroupsDeleteGroup (string authorization, string partitionKey, string rowKey);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        ApiResponse<OAuth2ApiResponseStrongUserGroupBean> GroupsDeleteGroupWithHttpInfo (string authorization, string partitionKey, string rowKey);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="memberRowKey"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        OAuth2ApiResponseStrongUserGroupBean GroupsDeleteGroupMember (string authorization, string partitionKey, string rowKey, string memberRowKey);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="memberRowKey"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        ApiResponse<OAuth2ApiResponseStrongUserGroupBean> GroupsDeleteGroupMemberWithHttpInfo (string authorization, string partitionKey, string rowKey, string memberRowKey);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <returns>OAuth2ApiResponseStrongListUserGroupBean</returns>
        OAuth2ApiResponseStrongListUserGroupBean GroupsListGroups (string authorization);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongListUserGroupBean</returns>
        ApiResponse<OAuth2ApiResponseStrongListUserGroupBean> GroupsListGroupsWithHttpInfo (string authorization);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        OAuth2ApiResponseStrongUserGroupBean GroupsLoadGroup (string authorization, string partitionKey, string rowKey);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        ApiResponse<OAuth2ApiResponseStrongUserGroupBean> GroupsLoadGroupWithHttpInfo (string authorization, string partitionKey, string rowKey);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="memberRowKey"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        OAuth2ApiResponseStrongUserGroupBean GroupsResendGroupInvitationEmail (string authorization, string partitionKey, string rowKey, string memberRowKey);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="memberRowKey"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        ApiResponse<OAuth2ApiResponseStrongUserGroupBean> GroupsResendGroupInvitationEmailWithHttpInfo (string authorization, string partitionKey, string rowKey, string memberRowKey);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="userGroupBean"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        OAuth2ApiResponseStrongUserGroupBean GroupsUpdateGroup (string authorization, string partitionKey, string rowKey, UserGroupBean userGroupBean);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="userGroupBean"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        ApiResponse<OAuth2ApiResponseStrongUserGroupBean> GroupsUpdateGroupWithHttpInfo (string authorization, string partitionKey, string rowKey, UserGroupBean userGroupBean);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class GroupsApi : IGroupsApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GroupsApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GroupsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public GroupsApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="activateGroupMembershipBean"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        public OAuth2ApiResponseStrongUserGroupBean GroupsActivateGroupMembership (string authorization, ActivateGroupMembershipBean activateGroupMembershipBean)
        {
             ApiResponse<OAuth2ApiResponseStrongUserGroupBean> localVarResponse = GroupsActivateGroupMembershipWithHttpInfo(authorization, activateGroupMembershipBean);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="activateGroupMembershipBean"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        public ApiResponse< OAuth2ApiResponseStrongUserGroupBean > GroupsActivateGroupMembershipWithHttpInfo (string authorization, ActivateGroupMembershipBean activateGroupMembershipBean)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling GroupsApi->GroupsActivateGroupMembership");
            // verify the required parameter 'activateGroupMembershipBean' is set
            if (activateGroupMembershipBean == null)
                throw new ApiException(400, "Missing required parameter 'activateGroupMembershipBean' when calling GroupsApi->GroupsActivateGroupMembership");

            var localVarPath = "/api/v1/groups/members/activate";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded", 
                "text/html"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (activateGroupMembershipBean != null && activateGroupMembershipBean.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(activateGroupMembershipBean); // http body (model) parameter
            }
            else
            {
                localVarPostBody = activateGroupMembershipBean; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GroupsActivateGroupMembership", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OAuth2ApiResponseStrongUserGroupBean>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OAuth2ApiResponseStrongUserGroupBean) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OAuth2ApiResponseStrongUserGroupBean)));
            
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="addGroupMemberBean"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        public OAuth2ApiResponseStrongUserGroupBean GroupsAddGroupMember (string authorization, string partitionKey, string rowKey, EmailAddressBean addGroupMemberBean)
        {
             ApiResponse<OAuth2ApiResponseStrongUserGroupBean> localVarResponse = GroupsAddGroupMemberWithHttpInfo(authorization, partitionKey, rowKey, addGroupMemberBean);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="addGroupMemberBean"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        public ApiResponse< OAuth2ApiResponseStrongUserGroupBean > GroupsAddGroupMemberWithHttpInfo (string authorization, string partitionKey, string rowKey, EmailAddressBean addGroupMemberBean)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling GroupsApi->GroupsAddGroupMember");
            // verify the required parameter 'partitionKey' is set
            if (partitionKey == null)
                throw new ApiException(400, "Missing required parameter 'partitionKey' when calling GroupsApi->GroupsAddGroupMember");
            // verify the required parameter 'rowKey' is set
            if (rowKey == null)
                throw new ApiException(400, "Missing required parameter 'rowKey' when calling GroupsApi->GroupsAddGroupMember");
            // verify the required parameter 'addGroupMemberBean' is set
            if (addGroupMemberBean == null)
                throw new ApiException(400, "Missing required parameter 'addGroupMemberBean' when calling GroupsApi->GroupsAddGroupMember");

            var localVarPath = "/api/v1/groups/{partitionKey}/{rowKey}/members";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded", 
                "text/html"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (partitionKey != null) localVarPathParams.Add("partitionKey", Configuration.ApiClient.ParameterToString(partitionKey)); // path parameter
            if (rowKey != null) localVarPathParams.Add("rowKey", Configuration.ApiClient.ParameterToString(rowKey)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (addGroupMemberBean != null && addGroupMemberBean.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(addGroupMemberBean); // http body (model) parameter
            }
            else
            {
                localVarPostBody = addGroupMemberBean; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GroupsAddGroupMember", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OAuth2ApiResponseStrongUserGroupBean>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OAuth2ApiResponseStrongUserGroupBean) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OAuth2ApiResponseStrongUserGroupBean)));
            
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="userGroupBean"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        public OAuth2ApiResponseStrongUserGroupBean GroupsCreateGroup (string authorization, UserGroupBean userGroupBean)
        {
             ApiResponse<OAuth2ApiResponseStrongUserGroupBean> localVarResponse = GroupsCreateGroupWithHttpInfo(authorization, userGroupBean);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="userGroupBean"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        public ApiResponse< OAuth2ApiResponseStrongUserGroupBean > GroupsCreateGroupWithHttpInfo (string authorization, UserGroupBean userGroupBean)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling GroupsApi->GroupsCreateGroup");
            // verify the required parameter 'userGroupBean' is set
            if (userGroupBean == null)
                throw new ApiException(400, "Missing required parameter 'userGroupBean' when calling GroupsApi->GroupsCreateGroup");

            var localVarPath = "/api/v1/groups";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded", 
                "text/html"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (userGroupBean != null && userGroupBean.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(userGroupBean); // http body (model) parameter
            }
            else
            {
                localVarPostBody = userGroupBean; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GroupsCreateGroup", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OAuth2ApiResponseStrongUserGroupBean>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OAuth2ApiResponseStrongUserGroupBean) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OAuth2ApiResponseStrongUserGroupBean)));
            
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        public OAuth2ApiResponseStrongUserGroupBean GroupsDeleteGroup (string authorization, string partitionKey, string rowKey)
        {
             ApiResponse<OAuth2ApiResponseStrongUserGroupBean> localVarResponse = GroupsDeleteGroupWithHttpInfo(authorization, partitionKey, rowKey);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        public ApiResponse< OAuth2ApiResponseStrongUserGroupBean > GroupsDeleteGroupWithHttpInfo (string authorization, string partitionKey, string rowKey)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling GroupsApi->GroupsDeleteGroup");
            // verify the required parameter 'partitionKey' is set
            if (partitionKey == null)
                throw new ApiException(400, "Missing required parameter 'partitionKey' when calling GroupsApi->GroupsDeleteGroup");
            // verify the required parameter 'rowKey' is set
            if (rowKey == null)
                throw new ApiException(400, "Missing required parameter 'rowKey' when calling GroupsApi->GroupsDeleteGroup");

            var localVarPath = "/api/v1/groups/{partitionKey}/{rowKey}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (partitionKey != null) localVarPathParams.Add("partitionKey", Configuration.ApiClient.ParameterToString(partitionKey)); // path parameter
            if (rowKey != null) localVarPathParams.Add("rowKey", Configuration.ApiClient.ParameterToString(rowKey)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GroupsDeleteGroup", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OAuth2ApiResponseStrongUserGroupBean>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OAuth2ApiResponseStrongUserGroupBean) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OAuth2ApiResponseStrongUserGroupBean)));
            
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="memberRowKey"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        public OAuth2ApiResponseStrongUserGroupBean GroupsDeleteGroupMember (string authorization, string partitionKey, string rowKey, string memberRowKey)
        {
             ApiResponse<OAuth2ApiResponseStrongUserGroupBean> localVarResponse = GroupsDeleteGroupMemberWithHttpInfo(authorization, partitionKey, rowKey, memberRowKey);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="memberRowKey"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        public ApiResponse< OAuth2ApiResponseStrongUserGroupBean > GroupsDeleteGroupMemberWithHttpInfo (string authorization, string partitionKey, string rowKey, string memberRowKey)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling GroupsApi->GroupsDeleteGroupMember");
            // verify the required parameter 'partitionKey' is set
            if (partitionKey == null)
                throw new ApiException(400, "Missing required parameter 'partitionKey' when calling GroupsApi->GroupsDeleteGroupMember");
            // verify the required parameter 'rowKey' is set
            if (rowKey == null)
                throw new ApiException(400, "Missing required parameter 'rowKey' when calling GroupsApi->GroupsDeleteGroupMember");
            // verify the required parameter 'memberRowKey' is set
            if (memberRowKey == null)
                throw new ApiException(400, "Missing required parameter 'memberRowKey' when calling GroupsApi->GroupsDeleteGroupMember");

            var localVarPath = "/api/v1/groups/{partitionKey}/{rowKey}/members/{memberRowKey}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (partitionKey != null) localVarPathParams.Add("partitionKey", Configuration.ApiClient.ParameterToString(partitionKey)); // path parameter
            if (rowKey != null) localVarPathParams.Add("rowKey", Configuration.ApiClient.ParameterToString(rowKey)); // path parameter
            if (memberRowKey != null) localVarPathParams.Add("memberRowKey", Configuration.ApiClient.ParameterToString(memberRowKey)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GroupsDeleteGroupMember", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OAuth2ApiResponseStrongUserGroupBean>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OAuth2ApiResponseStrongUserGroupBean) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OAuth2ApiResponseStrongUserGroupBean)));
            
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <returns>OAuth2ApiResponseStrongListUserGroupBean</returns>
        public OAuth2ApiResponseStrongListUserGroupBean GroupsListGroups (string authorization)
        {
             ApiResponse<OAuth2ApiResponseStrongListUserGroupBean> localVarResponse = GroupsListGroupsWithHttpInfo(authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongListUserGroupBean</returns>
        public ApiResponse< OAuth2ApiResponseStrongListUserGroupBean > GroupsListGroupsWithHttpInfo (string authorization)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling GroupsApi->GroupsListGroups");

            var localVarPath = "/api/v1/groups";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GroupsListGroups", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OAuth2ApiResponseStrongListUserGroupBean>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OAuth2ApiResponseStrongListUserGroupBean) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OAuth2ApiResponseStrongListUserGroupBean)));
            
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        public OAuth2ApiResponseStrongUserGroupBean GroupsLoadGroup (string authorization, string partitionKey, string rowKey)
        {
             ApiResponse<OAuth2ApiResponseStrongUserGroupBean> localVarResponse = GroupsLoadGroupWithHttpInfo(authorization, partitionKey, rowKey);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        public ApiResponse< OAuth2ApiResponseStrongUserGroupBean > GroupsLoadGroupWithHttpInfo (string authorization, string partitionKey, string rowKey)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling GroupsApi->GroupsLoadGroup");
            // verify the required parameter 'partitionKey' is set
            if (partitionKey == null)
                throw new ApiException(400, "Missing required parameter 'partitionKey' when calling GroupsApi->GroupsLoadGroup");
            // verify the required parameter 'rowKey' is set
            if (rowKey == null)
                throw new ApiException(400, "Missing required parameter 'rowKey' when calling GroupsApi->GroupsLoadGroup");

            var localVarPath = "/api/v1/groups/{partitionKey}/{rowKey}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (partitionKey != null) localVarPathParams.Add("partitionKey", Configuration.ApiClient.ParameterToString(partitionKey)); // path parameter
            if (rowKey != null) localVarPathParams.Add("rowKey", Configuration.ApiClient.ParameterToString(rowKey)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GroupsLoadGroup", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OAuth2ApiResponseStrongUserGroupBean>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OAuth2ApiResponseStrongUserGroupBean) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OAuth2ApiResponseStrongUserGroupBean)));
            
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="memberRowKey"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        public OAuth2ApiResponseStrongUserGroupBean GroupsResendGroupInvitationEmail (string authorization, string partitionKey, string rowKey, string memberRowKey)
        {
             ApiResponse<OAuth2ApiResponseStrongUserGroupBean> localVarResponse = GroupsResendGroupInvitationEmailWithHttpInfo(authorization, partitionKey, rowKey, memberRowKey);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="memberRowKey"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        public ApiResponse< OAuth2ApiResponseStrongUserGroupBean > GroupsResendGroupInvitationEmailWithHttpInfo (string authorization, string partitionKey, string rowKey, string memberRowKey)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling GroupsApi->GroupsResendGroupInvitationEmail");
            // verify the required parameter 'partitionKey' is set
            if (partitionKey == null)
                throw new ApiException(400, "Missing required parameter 'partitionKey' when calling GroupsApi->GroupsResendGroupInvitationEmail");
            // verify the required parameter 'rowKey' is set
            if (rowKey == null)
                throw new ApiException(400, "Missing required parameter 'rowKey' when calling GroupsApi->GroupsResendGroupInvitationEmail");
            // verify the required parameter 'memberRowKey' is set
            if (memberRowKey == null)
                throw new ApiException(400, "Missing required parameter 'memberRowKey' when calling GroupsApi->GroupsResendGroupInvitationEmail");

            var localVarPath = "/api/v1/groups/{partitionKey}/{rowKey}/members/{memberRowKey}/resend";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (partitionKey != null) localVarPathParams.Add("partitionKey", Configuration.ApiClient.ParameterToString(partitionKey)); // path parameter
            if (rowKey != null) localVarPathParams.Add("rowKey", Configuration.ApiClient.ParameterToString(rowKey)); // path parameter
            if (memberRowKey != null) localVarPathParams.Add("memberRowKey", Configuration.ApiClient.ParameterToString(memberRowKey)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GroupsResendGroupInvitationEmail", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OAuth2ApiResponseStrongUserGroupBean>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OAuth2ApiResponseStrongUserGroupBean) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OAuth2ApiResponseStrongUserGroupBean)));
            
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="userGroupBean"></param>
        /// <returns>OAuth2ApiResponseStrongUserGroupBean</returns>
        public OAuth2ApiResponseStrongUserGroupBean GroupsUpdateGroup (string authorization, string partitionKey, string rowKey, UserGroupBean userGroupBean)
        {
             ApiResponse<OAuth2ApiResponseStrongUserGroupBean> localVarResponse = GroupsUpdateGroupWithHttpInfo(authorization, partitionKey, rowKey, userGroupBean);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">Bearer AccessToken</param>
        /// <param name="partitionKey"></param>
        /// <param name="rowKey"></param>
        /// <param name="userGroupBean"></param>
        /// <returns>ApiResponse of OAuth2ApiResponseStrongUserGroupBean</returns>
        public ApiResponse< OAuth2ApiResponseStrongUserGroupBean > GroupsUpdateGroupWithHttpInfo (string authorization, string partitionKey, string rowKey, UserGroupBean userGroupBean)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling GroupsApi->GroupsUpdateGroup");
            // verify the required parameter 'partitionKey' is set
            if (partitionKey == null)
                throw new ApiException(400, "Missing required parameter 'partitionKey' when calling GroupsApi->GroupsUpdateGroup");
            // verify the required parameter 'rowKey' is set
            if (rowKey == null)
                throw new ApiException(400, "Missing required parameter 'rowKey' when calling GroupsApi->GroupsUpdateGroup");
            // verify the required parameter 'userGroupBean' is set
            if (userGroupBean == null)
                throw new ApiException(400, "Missing required parameter 'userGroupBean' when calling GroupsApi->GroupsUpdateGroup");

            var localVarPath = "/api/v1/groups/{partitionKey}/{rowKey}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "application/x-www-form-urlencoded", 
                "text/html"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json", 
                "text/json", 
                "application/xml", 
                "text/xml", 
                "text/html"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (partitionKey != null) localVarPathParams.Add("partitionKey", Configuration.ApiClient.ParameterToString(partitionKey)); // path parameter
            if (rowKey != null) localVarPathParams.Add("rowKey", Configuration.ApiClient.ParameterToString(rowKey)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (userGroupBean != null && userGroupBean.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(userGroupBean); // http body (model) parameter
            }
            else
            {
                localVarPostBody = userGroupBean; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GroupsUpdateGroup", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<OAuth2ApiResponseStrongUserGroupBean>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (OAuth2ApiResponseStrongUserGroupBean) Configuration.ApiClient.Deserialize(localVarResponse, typeof(OAuth2ApiResponseStrongUserGroupBean)));
            
        }

    }
}
